#!/usr/bin/env python3
"""Genera i tre Localizable.strings (it/es/en) dell'app da una lista sola,
cosi' le tre lingue restano sincronizzate e non si perde una chiave per
distrazione trascrivendo a mano centinaia di righe.

it.lproj riceve SOLO le voci marcate O2O3=True (le esplicite NSLocalizedString
e i due punti O2): per le altre l'italiano e' gia' la chiave stessa (D1), non
serve una tabella che ripeta la chiave come valore.

Si lancia dalla radice del progetto (o della copia):

    ./.venv/bin/python app/Localizzazioni/genera_strings.py app/Localizzazioni

VOCI e' l'unica fonte di verita': una chiave nuova o una traduzione da
cambiare si tocca solo qui, mai nei tre .strings direttamente (le tre tabelle
in git sono l'ultimo output di questo script, non un secondo posto dove
scrivere - [LINGUA-2]: prima di questo commit lo script viveva solo nello
scratchpad della sessione e spariva con lei, mentre le tabelle dicevano di
rigenerare con uno script che nessuno aveva in git).
"""
import subprocess
import sys

# (chiave_it, es, en, commento, o2o3)
VOCI = [
    # ---- Finestra.swift ----
    ("Il Mac sta finendo la memoria (libera il %lld%%)",
     "El Mac se está quedando sin memoria (libera el %lld%%)",
     "The Mac is running out of memory (free %lld%%)",
     "Memoria.swift: soglia critica", False),
    ("Memoria stretta: libera il %lld%%",
     "Memoria justa: libera el %lld%%",
     "Memory is tight: free %lld%%",
     "Memoria.swift: soglia stretta", False),
    ("Cosi' la guida parte e poi si ferma a meta', e sembra rotta. Chiudi Chrome, metti in pausa Google Drive e chiudi le sessioni che non ti servono, poi riprova.",
     "Así la guía arranca y se para a medias, y parece rota. Cierra Chrome, pausa Google Drive y cierra las sesiones que no necesites, y vuelve a intentarlo.",
     "This way the guide starts and then stalls halfway, and looks broken. Close Chrome, pause Google Drive and close the sessions you don't need, then try again.",
     "", False),
    ("I tempi che misuri adesso non sono quelli veri: la macchina sta scambiando memoria col disco.",
     "Los tiempos que midas ahora no son los reales: la máquina está intercambiando memoria con el disco.",
     "The times you measure now aren't the real ones: the machine is swapping memory to disk.",
     "", False),
    ("Prima di accendere manca qualcosa",
     "Antes de encender falta algo",
     "Something is missing before you can turn it on",
     "titolo Scheda", False),
    ("Prepara la macchina",
     "Prepara la máquina",
     "Prepare the machine",
     "", False),
    ("Ricontrolla",
     "Volver a comprobar",
     "Check again",
     "", False),
    ("Spegni la guida",
     "Apagar la guía",
     "Turn off the guide",
     "", False),
    ("Accendi la guida",
     "Encender la guía",
     "Turn on the guide",
     "", False),
    ("il primo avvio prende un minuto: carica i modelli e li scalda, cosi' il primo visitatore non paga l'attesa",
     "el primer arranque tarda un minuto: carga los modelos y los calienta, así el primer visitante no paga la espera",
     "the first startup takes a minute: it loads the models and warms them up, so the first visitor doesn't pay the wait",
     "O2: era una concatenazione con '+', ora un letterale solo", False),
    ("%lld passaggi nell'indice",
     "%lld pasajes en el índice",
     "%lld chunks in the index",
     "", False),
    ("· accesa da %@, parte da sola al login",
     "· encendida por %@, arranca sola al iniciar sesión",
     "· turned on by %@, starts on its own at login",
     "%@ e' il nome dell'agente (es. \"launchd (com.olivera.voice)\"), non si traduce", False),
    ("· accesa da qualcos'altro, non da questa app",
     "· encendida por otra cosa, no por esta app",
     "· turned on by something else, not this app",
     "", False),
    ("Su Unity puoi premere Play",
     "En Unity puedes pulsar Play",
     "In Unity you can press Play",
     "titolo Scheda; \"Unity\" e \"Play\" non si traducono", False),
    ("Con il campo host vuoto il visore trova il Mac da solo. Se preferisci essere sicuro, scrivi questo indirizzo in OliveraGuide:",
     "Con el campo host vacío el visor encuentra el Mac solo. Si prefieres estar seguro, escribe esta dirección en OliveraGuide:",
     "With the host field empty the headset finds the Mac on its own. If you'd rather be sure, write this address in OliveraGuide:",
     "\"OliveraGuide\" non si traduce", False),
    ("Il discovery e' spento su questo Mac: l'indirizzo va scritto a mano nel campo host di OliveraGuide.",
     "El discovery está apagado en este Mac: la dirección hay que escribirla a mano en el campo host de OliveraGuide.",
     "Discovery is off on this Mac: the address has to be typed by hand into OliveraGuide's host field.",
     "", False),
    ("copiato",
     "copiado",
     "copied",
     "", False),
    ("copia",
     "copiar",
     "copy",
     "", False),
    ("WebSocket",
     "WebSocket",
     "WebSocket",
     "nome di protocollo, non si traduce", False),
    ("Prova nel browser",
     "Probar en el navegador",
     "Try in the browser",
     "", False),
    ("La prima volta macOS chiede se lasciar passare le connessioni in entrata: bisogna dire di si', se no il visore non arriva.",
     "La primera vez macOS pregunta si dejar pasar las conexiones entrantes: hay que decir que sí, si no el visor no llega.",
     "The first time, macOS asks whether to let incoming connections through: you have to say yes, otherwise the headset can't reach it.",
     "", False),
    ("Prova senza visore",
     "Prueba sin visor",
     "Test without headset",
     "titolo Scheda", False),
    ("Manda un ordine e una domanda. L'ordine deve tornare come azione: se torna a parole, il server sta girando su codice vecchio.",
     "Envía una orden y una pregunta. La orden debe volver como acción: si vuelve como palabras, el servidor está corriendo código viejo.",
     "Sends a command and a question. The command must come back as an action: if it comes back as words, the server is running old code.",
     "", False),
    ("provo...",
     "probando...",
     "testing...",
     "", False),
    ("Prova adesso",
     "Probar ahora",
     "Test now",
     "", False),
    ("Voce",
     "Voz",
     "Voice",
     "etichetta Picker", False),
    ("Modello",
     "Modelo",
     "Model",
     "etichetta Picker", False),
    ("Fatti trovare dal visore in automatico",
     "Déjate encontrar por el visor automáticamente",
     "Let the headset find you automatically",
     "", False),
    ("Spegnilo quando anche il PC ha il suo server acceso: se rispondono in due, Unity ne prende uno a caso.",
     "Apágalo cuando el PC también tenga su servidor encendido: si responden dos, Unity elige uno al azar.",
     "Turn it off when the PC also has its server on: if two answer, Unity picks one at random.",
     "", False),
    ("I cambiamenti valgono al prossimo avvio.",
     "Los cambios valen a partir del próximo arranque.",
     "Changes take effect on the next start.",
     "", False),
    # [LINGUA-2] / D10 (critica C4): sotto un agente launchd la frase sopra e'
    # falsa - i cambiamenti non valgono al "prossimo avvio" di questa app, ma
    # a quando l'agente la fa ripartire lui. Ternario di due letterali in
    # Finestra.swift: entrambi vanno in tabella, l'italiano compreso, perche'
    # la scelta e' la stessa forma O2 (ternario di stringhe) gia' usata per
    # "%lld documenti, %lld passaggi" e simili.
    ("I cambiamenti valgono quando l'agente riparte.",
     "Los cambios valen cuando el agente vuelve a arrancar.",
     "Changes take effect when the agent restarts.",
     "D10, ternario in Preferenze secondo se il custode e' l'agente launchd", False),
    ("Come deve parlare",
     "Cómo debe hablar",
     "How it should talk",
     "titolo DisclosureGroup Preferenze", False),
    ("Manda lo stesso richiamo che manda il visore e ascolta chi risponde. Se rispondono in due, la scelta di Unity non e' prevedibile.",
     "Envía la misma llamada que envía el visor y escucha quién responde. Si responden dos, la elección de Unity no es predecible.",
     "Sends the same call the headset sends and listens for who answers. If two answer, Unity's choice isn't predictable.",
     "", False),
    ("ascolto...",
     "escuchando...",
     "listening...",
     "", False),
    ("Chi risponde sulla rete",
     "Quién responde en la red",
     "Who answers on the network",
     "", False),
    ("  (questo Mac)",
     "  (este Mac)",
     "  (this Mac)",
     "O2: suffisso annidato in un'interpolazione, non lo localizza SwiftUI da solo - NSLocalizedString esplicito", True),
    ("Rispondono in %lld: spegni il discovery su quello che non deve prendersi il visore.",
     "Responden %lld: apaga el discovery en el que no debe quedarse con el visor.",
     "%lld are answering: turn off discovery on the one that shouldn't take the headset.",
     "", False),
    ("Chi c'e' sulla rete",
     "Quién hay en la red",
     "Who's on the network",
     "titolo DisclosureGroup Rete", False),
    ("Registro",
     "Registro",
     "Log",
     "titolo DisclosureGroup Registro", False),
    # ---- Documenti.swift ----
    ("Su cosa si basa",
     "En qué se basa",
     "What it's based on",
     "titolo DisclosureGroup Documenti", False),
    ("leggo l'elenco...",
     "leyendo la lista...",
     "reading the list...",
     "", False),
    ("Non disponibile: il server sta girando su codice vecchio.",
     "No disponible: el servidor está corriendo código viejo.",
     "Not available: the server is running old code.",
     "", False),
    ("Non disponibile: il server non ha risposto (codice %lld).",
     "No disponible: el servidor no ha respondido (código %lld).",
     "Not available: the server did not respond (code %lld).",
     "", False),
    ("%lld documenti, %lld passaggi",
     "%lld documentos, %lld pasajes",
     "%lld documents, %lld chunks",
     "", False),
    # ---- Motore.swift: Fase.descrizione (O3) ----
    ("spenta",
     "apagada",
     "off",
     "Fase.descrizione", True),
    ("pronta",
     "lista",
     "ready",
     "Fase.descrizione", True),
    # ---- Motore.swift: Voce (O3) ----
    ("Kokoro",
     "Kokoro",
     "Kokoro",
     "nome proprio, non si traduce", True),
    ("Di sistema",
     "Del sistema",
     "System",
     "", True),
    ("Clonata",
     "Clonada",
     "Cloned",
     "", True),
    ("neurale, 0,18 di fattore di tempo reale",
     "neuronal, factor de tiempo real de 0,18",
     "neural, 0.18 real-time factor",
     "", True),
    ("0,3 s piu' rapida, ma si sente che e' una macchina",
     "0,3 s más rápida, pero se nota que es una máquina",
     "0.3 s faster, but it's obviously a machine",
     "", True),
    ("fuori dal tempo reale su questo Mac: solo per ascoltarla",
     "fuera de tiempo real en este Mac: solo para escucharla",
     "not real-time on this Mac: for listening to it only",
     "", True),
    # ---- Motore.swift: Taglia (O3) ----
    ("4 bit",
     "4 bits",
     "4-bit",
     "", True),
    ("8 bit",
     "8 bits",
     "8-bit",
     "", True),
    ("prima frase in 0,9 s, 3,9 GB",
     "primera frase en 0,9 s, 3,9 GB",
     "first sentence in 0.9 s, 3.9 GB",
     "", True),
    ("risposte un filo migliori, +0,6 s e +1,2 GB",
     "respuestas un poco mejores, +0,6 s y +1,2 GB",
     "slightly better answers, +0.6 s and +1.2 GB",
     "", True),
    # ---- Motore.swift: varie String (O3) ----
    ("avvio...",
     "arrancando...",
     "starting...",
     "", True),
    ("chiedo a %@ di accenderla...",
     "le pido a %@ que la encienda...",
     "asking %@ to turn it on...",
     "%@ e' il nome dell'agente, non si traduce", True),
    ("[agente]",
     "[agente]",
     "[agente]",
     "prefisso tecnico di log, come [olivera] in Python: resta uguale nelle tre lingue", True),
    ("nessun dettaglio",
     "sin detalles",
     "no details",
     "", True),
    ("non e' partita: %@",
     "no arrancó: %@",
     "did not start: %@",
     "", True),
    ("si e' fermata (codice %lld)",
     "se detuvo (código %lld)",
     "stopped (code %lld)",
     "", True),
    ("non parte: %@",
     "no arranca: %@",
     "won't start: %@",
     "error.localizedDescription, gia' nella lingua di sistema", True),
    ("il server e' acceso da qualcos'altro: spegnilo da dove l'hai avviato",
     "el servidor lo encendió otra cosa: apágalo desde donde lo arrancaste",
     "the server was turned on by something else: turn it off from wherever you started it",
     "", True),
    ("non risponde piu': l'agente potrebbe averla riavviata, riprovo...",
     "ya no responde: puede que el agente la haya reiniciado, reintentando...",
     "not responding anymore: the agent may have restarted it, retrying...",
     "", True),
    ("non risponde alla salute",
     "no responde a la salud",
     "not answering the health check",
     "", True),
    ("la prova non ha risposto",
     "la prueba no respondió",
     "the test did not respond",
     "", True),
    ("non risponde: %@",
     "no responde: %@",
     "not responding: %@",
     "", True),
    ("ordine eseguito (%@ %@) in %lld ms",
     "orden ejecutada (%@ %@) en %lld ms",
     "command executed (%@ %@) in %lld ms",
     "", True),
    ("ORDINE NON ESEGUITO: ha risposto a parole. Il server gira su codice vecchio.",
     "ORDEN NO EJECUTADA: respondió con palabras. El servidor corre código viejo.",
     "COMMAND NOT EXECUTED: it answered in words. The server is running old code.",
     "", True),
    ("domanda: primo suono in %@ s",
     "pregunta: primer sonido en %@ s",
     "question: first sound in %@ s",
     "", True),
    ("preparo (scarica qualche centinaio di MB)...",
     "preparando (descarga unos cientos de MB)...",
     "preparing (downloads a few hundred MB)...",
     "", True),
    # ---- Piattaforma.swift: Requisito.nome (O3) ----
    ("ambiente Python",
     "entorno Python",
     "Python environment",
     "", True),
    ("pesi dell'ascolto",
     "pesos del oído",
     "listening weights",
     "", True),
    ("pesi della voce",
     "pesos de la voz",
     "voice weights",
     "", True),
    ("indice del corpus",
     "índice del corpus",
     "corpus index",
     "", True),
]


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def scrivi(percorso: str, lingua: str, solo_o2o3: bool) -> None:
    righe = ['/* Generato da app/Localizzazioni/genera_strings.py - lotto LINGUA. */',
             '/* Non modificare a mano: rigenera con lo script se serve cambiare una voce. */', '']
    for chiave, es, en, commento, o2o3 in VOCI:
        if solo_o2o3 and not o2o3:
            continue
        valore = {"es": es, "en": en, "it": chiave}[lingua]
        if commento:
            righe.append(f"/* {commento} */")
        righe.append(f'"{escape(chiave)}" = "{escape(valore)}";')
        righe.append("")
    with open(percorso, "w", encoding="utf-8") as fh:
        fh.write("\n".join(righe))


if __name__ == "__main__":
    base = sys.argv[1]
    scrivi(f"{base}/it.lproj/Localizable.strings", "it", solo_o2o3=True)
    scrivi(f"{base}/es.lproj/Localizable.strings", "es", solo_o2o3=False)
    scrivi(f"{base}/en.lproj/Localizable.strings", "en", solo_o2o3=False)
    print(f"scritte {len(VOCI)} voci ({sum(1 for v in VOCI if v[4])} in it.lproj)")
